version: "3.5"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  graphql:
    build:
      context: ./graphql
      dockerfile: Dockerfile
    command: "npm run start:watch"
    volumes:
      - "./graphql:/app"
      - "/usr/src/app/node_modules"
    ports:
      - "3001:3000"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
      - MONGO_URI=${MONGO_URI:-mongodb://mongo}
      - MONGO_NAME=${MONGO_NAME:-test}
      - SECRET=${SECRET:-abc123}
      # - MOCKS=false
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    volumes:
      - "./admin:/app"
      - "/usr/src/app/node_modules"
    ports:
      - "3002:3000"
    depends_on:
      - graphql
    links:
      - graphql
    environment:
      - NODE_ENV=development
      - REACT_APP_WEDDING_DATE=9/15/19
      - REACT_APP_APOLLO_CLIENT=http://localhost:3001/graphql
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    volumes:
      - "./ui:/app"
      - "/usr/src/app/node_modules"
    ports:
      - "3003:3000"
    depends_on:
      - graphql
    links:
      - graphql
    environment:
      - NODE_ENV=development
      - REACT_APP_APOLLO_CLIENT=http://localhost:3001/graphql
      - REACT_APP_WEDDING_DATE=9/15/19
